### ISSUE TITLE
Document public key used for phar signing

### ISSUE THREAD

**Issue by lucc** [PHPCSStandards/PHP_CodeSniffer#157]
## Is your feature request related to a problem?

I want to install the phar with phive in CI. This means my script needs to run without user interaction.  For this I hard code the signing key that phive should expect when installing phpcs.

## Describe the solution you'd like

Please document the key that is used to sign the phar in the README or some other obvious place in the documentation. Best would be any "install" section of the docs.

## Additional context (optional)

If the key is not documented any user that installs the phar can just verify that it is signed with *some* key.  The problem is that we have no way of knowing that the key is the intended one.

This is the same argument why browser do not accept self signed tls certificates.

- [ ] I intend to create a pull request to implement this feature.

**Comment by jrfnl** [comment]
What do you expect this documentation to contain ?

**Comment by lucc** [comment]
A comment like 
> The phars are singed with our official key: `abcdef0123`.
or so.

**Comment by jrfnl** [comment]
@theseer If you don't mind me asking - have you got any advise on what's best practice regarding the key documentation ?

**Comment by theseer** [comment]
From a security paranoid (tm) position, the most important aspect is to verify authenticity, e.g. publish the gpg key fingerprint on an unrelated medium - e.g. your website.

Since one cannot provide any interactive confirmation in CI to allow the import of a new public key to enable verification, it probably is a good idea to add the `--trust-gpg-keys` option as an example.

**Comment by theseer** [comment]
Also having an "install" section that also shows the expected output might be helpful, so an inexperienced user can follow it step by step and compare output.

**Comment by jrfnl** [comment]
> From a security paranoid (tm) position, the most important aspect is to verify authenticity, e.g. publish the gpg key fingerprint on an unrelated medium - e.g. your website.
> 
> Since one cannot provide any interactive confirmation in CI to allow the import of a new public key to enable verification, it probably is a good idea to add the `--trust-gpg-keys` option as an example.

@theseer I followed the steps [documented here](https://phar.io/howto/uploading-public-keys.html) when I created the key, so that means the key is available on https://keys.openpgp.org/
Am I correct in thinking that is what the `--trust-gpg-keys` is about ?

And, if I understand you correctly, I should also publish a `phpcs.pub` file on the http://phars.phpcodesniffer.com/ website ? Correct ?

> Also having an "install" section that also shows the expected output might be helpful, so an inexperienced user can follow it step by step and compare output.

Consider me an inexperienced PHIVE user, so I'm probably not the best person to write that section. @lucc Would you be up for providing a text for this which I could add to the wiki ? Or for making some tweaks to the README section about PHIVE ?

**Comment by theseer** [comment]
> > From a security paranoid (tm) position, the most important aspect is to verify authenticity, e.g. publish the gpg key fingerprint on an unrelated medium - e.g. your website.
> > Since one cannot provide any interactive confirmation in CI to allow the import of a new public key to enable verification, it probably is a good idea to add the `--trust-gpg-keys` option as an example.
> 
> @theseer I followed the steps [documented here](https://phar.io/howto/uploading-public-keys.html) when I created the key, so that means the key is available on https://keys.openpgp.org/ Am I correct in thinking that is what the `--trust-gpg-keys` is about ?

Yes, the key should be available on the aforementioned key server.
But no, `--trust-gpg-keys` is a means to bypass the manual confirmation step to import an otherwise unknown key as trusted. So you'd need to specify your key's ID here: `phive install --trust-gpg-keys 0x12345678901234567890 foo`.

> 
> And, if I understand you correctly, I should also publish a `phpcs.pub` file on the http://phars.phpcodesniffer.com/ website ? Correct ?

No, you should publish they Key ID (already implicitly done with the above call example) and the fingerprint. We, for instance, have that on our footer at phar.io.

> 
> > Also having an "install" section that also shows the expected output might be helpful, so an inexperienced user can follow it step by step and compare output.
> 
> Consider me an inexperienced PHIVE user, so I'm probably not the best person to write that section. @lucc Would you be up for providing a text for this which I could add to the wiki ? Or for making some tweaks to the README section about PHIVE ?

**Comment by jrfnl** [comment]
> Yes, the key should be available on the aforementioned key server. But no, `--trust-gpg-keys` is a means to bypass the manual confirmation step to import an otherwise unknown key as trusted. So you'd need to specify your key's ID here: `phive install --trust-gpg-keys 0x12345678901234567890 foo`.

@theseer thank you for your help! In PR #158, the key fingerprint is passed in the `phive` command, but I see you mention the `ID` here as a different entity. How would I go about figuring out what the ID is ? Or will the fingerprint work just as well ?
