### ISSUE TITLE
allow remote ruleset (i.e https://some-domain.com/path/to/ruleset.xml)

### ISSUE THREAD

**Issue by Asenar** [PHPCSStandards/PHP_CodeSniffer#515]
This feature will allow to include in our `phpcs.xml.dist` file remote ruleset, for example by adding the following in configuration:

```
<rule ref="https://raw.githubusercontent.com/squizlabs/PHP_CodeSniffer/master/phpcs.xml.dist" />
```

This feature will allow serveral company project to use a common base, either from their private repository, or from a public project

- [x] I intend to create a pull request to implement this feature.

**Comment by jrfnl** [comment]
@Asenar Thank you for your interest in contributing to PHP_CodeSniffer.

> This feature will allow several company project to use a common base, either from their private repository, or from a public project

I'm not sure I understand the need for this feature. After all, projects can already use a common base.

Typically, this is done by having a separate repo which is set up as an external coding standard for PHP CodeSniffer, which handles the dependencies and the ruleset.

The projects then add this external coding standard as a dependency and reference the standard by name in their own ruleset.

A setup like that, also allows for versioning the ruleset instead of it being a moving target (like it would be with a URL).

An example of such a setup can be seen in this organisation.
* There is a [`PHPCSDevCS`](https://github.com/PHPCSStandards/PHPCSDevCS) repo which manages the dependencies and holds the ruleset.
* All pre-existing projects in this repo, like PHPCSExtra, PHPCSUtils all use this external standard for their code style needs by requiring the dependency via [Composer](https://github.com/PHPCSStandards/PHPCSExtra/blob/6dcc44351983b9dbddf9012a3533804768ca4bbb/composer.json#L31) and then [using the external standard in their ruleset](https://github.com/PHPCSStandards/PHPCSExtra/blob/6dcc44351983b9dbddf9012a3533804768ca4bbb/phpcs.xml.dist#L35).

There are plenty of other examples of such a setup around too.

Allowing for a URL also feels like it could open projects up to security risks if they would point to a URL for a standard which is not under their control.

**Comment by Asenar** [comment]
You right, this can be achieved by different ways too.

I was thinking to a particular case where I didn't wanted to add a new dependency via composer (it's a documentation repository that hadn't any other purpose than to be read, but we can do differently).

**Comment by jrfnl** [comment]
@Asenar Glad to hear you've found another working solution. In that case, can we close this ticket ?

**Comment by Asenar** [comment]
It's not ideal for me but yes I will find other way, we can close it :).

Thanks for that so quick answer !
